[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
qstn_survey = "8kes5JBfEYSkMHqW2GywAMZWMVJUKPH5yS69DPHAUAQb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
